name: NarutoUHC
author: RqndomHax
version: 0.1
main: fr.rqndomhax.narutouhc.core.Main
load: POSTWORLD
depend: [ProtocolLib]
commands:
  help:
  rules:
  inventory:
  tpnaruto:
  revive:
  host:
    aliases: [h]
  msg:
    aliases:
      - whisper
      - tell
  heal:
  save:
  cancel:
  force:
  enchant:
  na:
    aliases: [naruto]
  admininventory:
    aliases: [ainv]